name: Clang Format Check

on: [pull_request]

jobs:
  clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Check clang-format on changed lines
      run: |
        git diff -U0 -r HEAD^1 HEAD | clang-format-diff-18 -p1 -style=file
